global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@example.com'

# Configuration des routes d'alertes
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook'

# Récepteurs d'alertes
receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://flask-app:5000/alerts'
        send_resolved: true

# Règles d'inhibition
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']