global:
  scrape_interval: 5s
  evaluation_interval: 5s

# Configuration Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Règles d'alerte
rule_files:
  - "alertrules.yml"

scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Votre application Flask
  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-app:5000']
    scrape_interval: 10s

  # Node Exporter pour les métriques système
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  # Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']